//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public int Number { get; set; }
        public string Color { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Piece { get; set; }
        public int GameId { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
